zuul:
  sensitive-headers:
  routes:
    aaaaa:
      path: /product/**
      serviceId: product
      sensitiveHeaders:
  ignored-patterns:
    - /myProduct/product/listForOrder
spring:
  application:
    name: api-gateway
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
