zuul:
  routes:
    aaaaa:
      path: /myproduct/**
      serviceId: product
      sensitiveHeaders:
#   ignored-patterns:
#     - /**/product/listForOrder
spring:
  application:
    name: api-gateway
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
