zuul:
  routes:
    aaaaa:
      path: /abc/**
      serviceId: product
      sensitiveHeaders:
spring:
  application:
    name: api-gateway
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
