spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
    
server:
  port: 8081
env:
  dev
girl:
  name: eee
  age: 18
